const Routes = {
    // EXAMPLE: require("your path") | File
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    SIGNUP_SCREEN: 'SIGNUP_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    DASHBOARD_STACK: 'DASHBOARD_STACK',
    AUTH_STACK: 'AUTH_STACK',
    GET_STARTED_SCREEN: 'GET_STARTED_SCREEN',
    ENABLE_LOCATION: 'ENABLE_LOCATION',
    MENU_SCREEN: 'MENU_SCREEN',
    BOTTOM_TAB: "BOTTOM_TAB",
    CART_SCREEN: 'CART_SCREEN',
    SEARCH_SCREEN: 'SEARCH_SCREEN',
}
export default Routes